### PR TITLE
added a dockerfile version to avoid 'connection closed: RPC failed' e…

### PR DESCRIPTION
**Pull request by Mou97**
…rror when cloning big repos.
Detailed error: error: RPC failed; curl transfer closed with outstanding read data remaining
Explanation: this error is due to low internet when cloning a big repository, 
Solution: it can be solved by doing a shallow clone to the repo first then fetching the rest of the data later.

### CODE REVIEW

**Comment by Overv** [comment]
We really shouldn't have a separate Dockerfile for this. The better solution would be to edit the existing Dockerfile to always do a shallow clone.

**Comment by Mou97** [comment]
resolved the changed. the shallow clone is now on the main Dockerfile

**Comment by Overv** [comment]
What is the purpose of the `git fetch --unshallow`?

**Comment by Mou97** [comment]
this command will convert the shallow clone to a regular one. 
the reason for using this is avoid any conflicts if the some dependency is using an older version of a repo (switching to an older commit maybe). just a precaution not to break anything.

**Comment by Overv** [comment]
I'm not sure what you mean. Doing a full clone right before deleting the .git directory seems kinda pointless to me.

**Comment by Mou97** [comment]
I agree, my bad. i didn't notice the git folder later was deleted few lines after.

**Comment by Overv** [comment]
In your latest commit you added another shallow fetch but that one doesn't work since the command immediately after that checks out a specific branch. I've fixed that and will merge now.

**Pull request merged**
