### PR TITLE
Add CI for openstreetmap-tile-server

### PR DESCRIPTION
**Pull request by Gjacquenot**
This PR:

- simplifies and homogenizes the Dockerfile
- reduces the final image size (from 4.7Gb to 3.88Gb)
- adds continuous integration with .travis.yml that deploy the container on dockerhub
- adds badges in main Readme.md (path will have to be updated to match this repo)
- upgrade postgis from 3.0.0rc2 to 3.0.0

To use continuous integration with travis, one will have to create a travis account, update the .travis.yml (replace `jacquenot` with `overv`, replace the DOCKER_PASSWORD)

One could reduce significantly the container size using intermediate container, so that we do not have an unneeded compiler at runtime.

Result of CI can be seen [here](https://travis-ci.org/Gjacquenot/openstreetmap-tile-server/builds/628915047)

### CODE REVIEW

**Comment by Istador** [comment]
I'm no expert with Travis-CI, but I think you exposed your personal secret token inside the `.travis.yml`.

**Comment by Gjacquenot** [comment]
@Istador , you are right it is encrypted with `travis encrypt` function. Documentation on how to encrypt passwords is [here](https://docs.travis-ci.com/user/encryption-keys/#usage)

**Comment by RZSenfo** [comment]
https://github.com/Gjacquenot/openstreetmap-tile-server/blob/a90f8f1d8c09d7b3e4c4c95875ff877a321704dd/Dockerfile#L161

Can't be linked because it's delete in line 119

**Comment by Gjacquenot** [comment]
@RZSenfo thanks for catching this, it can be solved by removing line [119](https://github.com/Gjacquenot/openstreetmap-tile-server/blob/a90f8f1d8c09d7b3e4c4c95875ff877a321704dd/Dockerfile#L119)

I dit not notice any problem, but I will fix this!

**Comment by Overv** [comment]
This looks pretty good. I haven't used Travis CI before, but let's give this a shot.

**Pull request merged**
