### PR TITLE
pull request solves issues #63 #64 #65

### PR DESCRIPTION
**Pull request by stevo01**

### CODE REVIEW

**Comment by stevo01** [comment]
Hi,
thanks for review. I change directory to "/nodes".

**Comment by Overv** [comment]
@stevo01 If make it work when `/nodes` doesn't exist then I can merge the PR.

**Comment by stevo01** [comment]
I put the creation of folder /nodes to Dockerfile. Additional the owner of the directory is changed to rednerer. I cleanup the commits, tested the patch with "import with flatnode option" on my workstation and hope I missed nothing ...

**Comment by Overv** [comment]
@stevo01 Right now the owner is only properly set if people don't mount `/nodes` themselves. Could you move the `chown` part to the `run.sh` script so that it always happens before startup?

**Comment by stevo01** [comment]
> @stevo01 Right now the owner is only properly set if people don't mount `/nodes` themselves. 

Are you sure? I performed a test and attached two logfiles. 

- import.txt shows start of import procedure. 
- check_permissions.txt, line 17 shows that  owner of directory /nodes is user "renderer".

[import.txt](https://github.com/Overv/openstreetmap-tile-server/files/3649109/import.txt)
[check_permissions.txt](https://github.com/Overv/openstreetmap-tile-server/files/3649115/check_permissions.txt)

**Comment by Overv** [comment]
Looks like you're right! The group id does become "UNKNOWN" if the nodes folder is a folder that you mount from your local hard drive rather than a named volume, but that doesn't look like a problem to me.

**Pull request merged**
