### PR TITLE
Documentation improvement to help users create their own map styles

### PR DESCRIPTION
**Pull request by floongle**
Based on discussions here: https://github.com/Overv/openstreetmap-tile-server/issues/42 I've created the following edit to the readme to help users take this docker file and use it to create their own styled maps.

### CODE REVIEW

**Comment by Overv** [comment]
I don't really like this approach because it will break as soon as the container is recreated for any reason. It would be better to use an explicit volume mount to include an alternative `mapnik.xml`. I also think that you may run into problems with this approach because the import will be based on a different stylesheet than the one that's actually being used for rendering.

**Comment by floongle** [comment]
Ok makes sense! After Christmas I'll look into what you describe and create a new version.

(hould we close this pull request and I submit a new one later? Or can this be modified? (it's all new to me so am learning as I go.)

**Comment by Istador** [comment]
> I spent some time wondering why when I updated the carto files in your docker container the pngs didn't update. Only when I edited the mapnik.xml file (which seems to replicate the work of the carto files in a different format) did things start to change. Presumably it's possible to use these carto files, but I couldn't spot how to do it. If you could point me in the right direction that would help in my quest to update the docs :)

Afaik the carto files are used to generate the `mapnik.xml` by using the `carto` command. When you change it, you need to re-generate the `mapnik.xml` again. It's used in the [Dockerfile](https://github.com/Overv/openstreetmap-tile-server/blob/789ff772bea1a52584e289c2d1d2930391be263e/Dockerfile#L127).

**Comment by floongle** [comment]
D'oh! That'd explain it, thank you! :)

**Comment by mylastore** [comment]
are all style files and mapnik.xml in this directory "home/renderer/src" for this Docker image?

**Comment by ftballguy45** [comment]
Any updates on this?

**Comment by galewis2** [comment]
This will get done via https://github.com/Overv/openstreetmap-tile-server/pull/243

**Pull request closed without merging**
