### PR TITLE
allow external PBF file with auto-downloader

### PR DESCRIPTION
**Pull request by skydiablo**

### CODE REVIEW

**Comment by Overv** [comment]
I'm not sure if it makes sense to include this kind of functionality in the image since the Luxembourg thing is really there as a demo and nothing else.

**Comment by skydiablo** [comment]
this allow to bring this docker image in an easy way to kubernetes. so, i do not need/can download the data.osm.pbf file to my local disk and mount it into the docker-image...

**Comment by Istador** [comment]
It also eases the creation process. You don't have to download, mount and later delete the file, and it becomes less likely to wrongly mount the PBF file as a volume, especially on windows systems.

I'd maybe even reduce both down to one parameter `DL_REGION`:
```bash
if [ ! -f /data.osm.pbf ]; then
  if [ ! -z "$(DL_PBF)" ]; then
    >&2 echo "WARNING: No import file at /data.osm.pbf, so importing Luxembourg as example..."
  fi
  DL_REGION=${DL_REGION:-europe/luxembourg}
  DL_PBF=${DL_PBF:-http://download.geofabrik.de/${DL_REGION}-latest.osm.pbf}
  DL_PBF_POLY=${DL_PBF_POLY:-http://download.geofabrik.de/${DL_REGION}.poly}

  # download pbf
  echo "INFO: Download PBF file: $DL_PBF"
  wget -nv "$(DL_PBF)" -O /data.osm.pbf

  # download poly
  echo "INFO: Download PBF-POLY file: $(DL_PBF_POLY)"
  wget -nv "$(DL_PBF_POLY)" -O /data.poly
fi
```

**Comment by Overv** [comment]
Fair enough, I'll review this PR later this week.

**Comment by Overv** [comment]
Could you fix the indentation? Other than that I'd be glad to merge this.

**Comment by Istador** [comment]
> @Istador I think this would make the image too reliant on the conventions of geofabrik.de.

Yes, that's partly true. It depends on how they name and structure it, but it's pretty straightforward and logical: `region`, `region/country`, or `region/country/state`.

And if a user decides to not want to use geofabrik, they don't have to provide an `DL_REGION` but can still give `DL_PBF` and `DL_PBF_POLY` directly (the way I wrote it, it only uses `DL_REGION` for the URL, if `DL_PBF` and `DL_PBF_POLY` aren't given, because of the `:-` fallback).

**Pull request merged**
