### PR TITLE
fix naciscdn.org

### PR DESCRIPTION
**Pull request by prih**
replace naciscdn.org
to https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip

### CODE REVIEW

**Comment by Overv** [comment]
Thanks for the fix! Fixes #211.

**Comment by endianjoakim** [comment]
I'm running `v1.7.4` from Docker hub and I'm still getting 
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='naciscdn.org', port=443): Max retries exceeded with url: /naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc7555f3220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
Was the correct dockerfile used to generate this image?

**Comment by Istador** [comment]
> I'm running `v1.7.4` from Docker hub and I'm still getting
> 
> [...]
> 
> Was the correct dockerfile used to generate this image?

Doesn't seem so.

According to [hub.docker.com](https://hub.docker.com/layers/overv/openstreetmap-tile-server/v1.7.4/images/sha256-224474c71463111a53a962d5af59938620e15704ca160bb430d064f43a9055f9?context=explore), the image layer 14 was build with the following command:
```
/bin/sh -c mkdir -p /home/renderer/src && cd /home/renderer/src && git clone --single-branch --branch v5.3.1 https://github.com/gravitystorm/openstreetmap-carto.git --depth 1 && cd openstreetmap-carto && rm -rf .git && npm install -g carto@0.18.2 && carto project.mml > mapnik.xml
```

So, the `sed` command is missing from
https://github.com/Overv/openstreetmap-tile-server/blob/0a4d079b0815cf7640ae4050642d8509e6ce552f/Dockerfile#L129-L136

**Comment by Overv** [comment]
Sorry, should be fixed now.

**Comment by timothyosm** [comment]
Using `overv/openstreetmap-tile-server:v1.7.4` i still seem to be running into the same error. I

**Comment by Istador** [comment]
> Using `overv/openstreetmap-tile-server:v1.7.4` i still seem to be running into the same error. I

Because the tag was updated, make sure that you pull the updated version. Otherwise you still use the old version on your machine. By default docker only pulls images/tags it doesn't have locally and never updates them (by the way this also applies when you use `latest`, your local version might be years old depending on your last pull).

Update:
- `docker pull overv/openstreetmap-tile-server:v1.7.4`
- When using `docker-compose` you can also use `docker-compose pull`.
- When you're building your own image based on it, you'll need to rebuild it with `docker build` or `docker-compose build`.

Make sure that you use the new image:
- When reusing containers with `docker start` / `docker stop` you'll need to `rm` the container and create a new one with `docker run`.
- When you only use `docker-compose stop`, `docker-compose start` and `docker-compose restart`, you'll also need to recreate the container. Make sure to use `docker-compose up -d` (or `docker-compose up --no-start`) to recreate the container with the new local version that you pulled.

**Comment by timothyosm** [comment]
Thanks mate, that's a great explanation!

**Pull request merged**
