### PR TITLE
Initialize postgres cluster if the cluster storage directory is empty

### LINKED ISSUE #94: PostgreSQL: directory is not a database cluster directory
When running
```
docker run -v /tank/maps/data.osm.pbf:/data.osm.pbf -v /tank/maps/data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server import
```
I get
```
+ service postgresql start
 * Starting PostgreSQL 12 database server
 * Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1:
pg_ctl: directory "/var/lib/postgresql/12/main" is not a database cluster directory
[.. everything failing because postgresql is down]
```
and indeed, the data folder is empty. Why?

### PR DESCRIPTION
**Pull request by dbahrdt**
This fixed #94 for me (apart from setting the correct permissions on the corresponding directory on the host.

### CODE REVIEW

**Comment by skydiablo** [comment]
hm, this is not working. checkout my logs:

> + '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
> + echo 'Initializing postgres cluster'
> + sudo -u postgres /usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main/ initdb -o '--locale C.UTF-8'
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> The database cluster will be initialized with locale "C.UTF-8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> Data page checksums are disabled.
> initdb: error: directory "/var/lib/postgresql/12/main" exists but is not empty
> It contains a lost+found directory, perhaps due to it being a mount point.
> Using a mount point directly as the data directory is not recommended.
> Create a subdirectory under the mount point.
> pg_ctl: database system initialization failed
> + exit 1

maybe we can change the mountpoint to parent directory?

**Comment by dbahrdt** [comment]
If you mounted your db-volume/bind-mount to `/var/lib/postgresql/12/` instead, then this should work again. At least the error message kind of suggests what went wrong. Maybe I'll look into better error handling if I encounter more errors. I'm currently in the process of setting-up a tileserver with a planet import with updates. For this I also tweaked the run.sh file a bit to have different postgres-configs during import and serving tiles.

**Comment by Derkades** [comment]
It seems like a basically identical fix was applied in https://github.com/Overv/openstreetmap-tile-server/commit/5a1b2a6b0655bfa7a9cddbd97f806d590715db02 just now

**Comment by Overv** [comment]
I've extended this fix to cover the two problems with mounting host directories rather than Docker volumes:

* The directory permissions will be wrong for Postgres
* The database directory is empty and needs to be initialized

**Pull request closed without merging**
