### PR TITLE
integrate tirex render daemon(s

### PR DESCRIPTION
**Pull request by stevo01**

### CODE REVIEW

**Comment by cdbattags** [comment]
hmmm, @Overv, do we plan on getting this in?

**Comment by Istador** [comment]
I think this use case is better handled as an own project / fork.

Changing the underlying renderer is a big change.

Offering both in the same docker image bloats up the image size with additional installs that aren't needed at runtime.

When both renderers are suggested as valid ways to use this image, then it also increases the amount of support work required for this project. Because more and different things can go wrong.

Does `tirex` as it is implemented in the pull request work with the automatic update mechanism? Because the mechanism that is set up in this project, inside the `openstreetmap-tiles-update-expire` file, is explicitly set up to work together with `renderd`.

**Comment by stevo01** [comment]
> I think this use case is better handled as an own project / fork.

I perfer to contribute my ideas and patches to  https://github.com/Overv/openstreetmap-tile-server/ because I like to benefit from reviews and comments like yours :-)

> Changing the underlying renderer is a big change.

The renderer itself (mapnik) is not changed. Tirex just replaced the renderd application which comes with mod_tile. Both solutions share following interfaces to other components: 
- socket interface to mod_tile
- tilecache directory and metatile concept
see https://wiki.openstreetmap.org/wiki/Tirex/Renderd for further details

> Offering both in the same docker image bloats up the image size with additional installs that aren't needed at runtime.

I decided to support both in a single container to allow everyone to compare both solutions and perform benchmark tests. 

An alternative solution is the seperation of the services in single docker container.
- apache / mod_tile
- osm2psql (for import and updates of osm data)
- psql with postgis extensions (https://hub.docker.com/r/mdillon/postgis)
- tirex / mapnik
- renderd / mapnik

> When both renderers are suggested as valid ways to use this image, then it also increases the amount of support work required for this project. Because more and different things can go wrong.

I agree and I think we should use tirex by default after further tests of tirex and tirex [commands](https://wiki.openstreetmap.org/wiki/Tirex/Commands).

> Does `tirex` as it is implemented in the pull request work with the automatic update mechanism? Because the mechanism that is set up in this project, inside the `openstreetmap-tiles-update-expire` file, is explicitly set up to work together with `renderd`.

I tested the automatic update mechanism and it seems to work. The openstreetmap-tiles-update-expire script is not well documented and I try to find how to verify the update procedure and the tile expiry mechanism. Until today I found to dependency to renderd.

**Comment by Overv** [comment]
@steve01 How do you feel about there being two images (for a while) with either render daemon?

**Comment by stevo01** [comment]
> @steve01 How do you feel about there being two images (for a while) with either render daemon?

Thats fine for me.

**Comment by Overv** [comment]
Alright, I may have time to integrate it next weekend.

**Comment by Overv** [comment]
Unfortunately I won't have time to implement this for the time being.

**Pull request closed without merging**
