### PR TITLE
pgsql indexes

### PR DESCRIPTION
**Pull request by souladm**
Hi!
Adding indexes to some tables makes it faster.
Check run.sh pls. The remaining changes are not useful.

### CODE REVIEW

**Comment by Overv** [comment]
Could you include some performance comparisons?

**Comment by Istador** [comment]
As far as I can see, these are the official indexes suggested by [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/), the map style in use by this project.

Since we already clone the git repository of this style, we can just import the existing [indexes.sql](https://github.com/gravitystorm/openstreetmap-carto/blob/master/indexes.sql) file from the file system (under `/home/renderer/src/openstreetmap-carto/indexes.sql`) with `pgsql`, instead of replicating these indexes in this project.

This pull request also includes other changes that should not be merged directly (changing the maintainer, timezone, image owner, default region imported, ...).

**Comment by souladm** [comment]
Oh, thanks. Apparently, in a hurry, I did not see indexes.sql file. Sorry for carelessness :) 


От: "Robin C. Ladiges" <notifications@github.com> 
Кому: "Overv/openstreetmap-tile-server" <openstreetmap-tile-server@noreply.github.com> 
Копия: "kosar" <kosar@freedom.valor.ua>, "Author" <author@noreply.github.com> 
Отправленные: Вторник, 28 Май 2019 г 22:15:48 
Тема: Re: [Overv/openstreetmap-tile-server] pgsql indexes (#34) 



As far as I can see, these are the official indexes suggested by [ https://github.com/gravitystorm/openstreetmap-carto/ | openstreetmap-carto ] , the map style in use by this project. 

Since we already clone the git repository of this style, we can just import the existing [ https://github.com/gravitystorm/openstreetmap-carto/blob/master/indexes.sql | indexes.sql ] file from the file system (under /home/renderer/src/openstreetmap-carto/indexes.sql ) with pgsql , instead of replicating these indexes in this project. 

This pull request also includes other changes that should not be merged directly (changing the maintainer, timezone, image owner, default region imported, ...).

**Comment by Overv** [comment]
Could you submit a new pull request with just the suggested indexes?

**Comment by Istador** [comment]
To test out the performance of these indexes I imported hamburg-latest.pbf (33 MiB), which took ca. 1m 13s and resulted in a ~1.8 GiB postgres database.

Then I tried pre-rendering without and with the indexes imported, each case with one thread, four threads and eight threads.

This isn't a clean measurement, which means I didn't stop other CPU intensive processes running on the machine (16 cores, 16 GiB memory, SSD) and I run each config only once instead of measuring it several times to determine an average. Between runs I've thrown away everything and started with new containers and volumes (`docker-compose down -v`).

These are my results (running time per zoom level in seconds):
```
threads |    1        1   |   4        4    |   8        8    |
index   |    No       Yes |   No       Yes  |   No       Yes  |
--------+-----------------+-----------------+-----------------+
z3      |    0.8      0.5 |   0.80     0.59 |   0.78     0.59 |
z4      |    0.8      0.4 |   0.75     0.42 |   0.77     0.42 |
z5      |    0.9      0.4 |   0.90     0.46 |   0.95     0.45 |
z6      |    1.1      0.6 |   1.05     0.57 |   1.10     0.55 |
z7      |    1.1      0.6 |   1.05     0.70 |   1.09     0.61 |
z8      |    1.6      0.8 |   1.47     0.79 |   1.55     0.83 |
z9      |    1.7      0.9 |   1.67     0.88 |   1.73     0.93 |
z10     |   27.3     27.0 |  26.41    26.59 |  27.67    26.55 |
z11     |   33.6     33.1 |  27.41    27.42 |  27.31    27.19 |
z12     |   36.6     35.8 |  31.22    30.74 |  30.58    31.05 |
z13     |   49.7     48.2 |  28.28    27.02 |  28.39    27.53 |
z14     |   72.3     69.2 |  22.88    21.94 |  23.87    20.98 |
z15     |  124.0    122.1 |  31.79    29.40 |  20.75    16.72 |
z16     |  246.4    248.7 |  61.21    59.11 |  32.26    32.38 |
z17     |  740.5    755.8 | 179.99   181.13 |  97.93    98.27 |
z18     | 2095.1   2147.2 | 513.48   513.29 | 282.03   282.14 |
--------+-----------------+-----------------+-----------------+
total   | 3433.5   3491.3 | 930.36   921.05 | 578.76   567.19 |
```

Overall it's a bit faster with these indexes, but the effect is very minimal. On higher zoom levels it gets worse, especially with just one thread.

The indexes were generated within ~2 seconds and took up ~13 MiB for this small database. Under the assumption that it scales up linear, then that might be ~18 GiB for the whole planet. But a city probably isn't a good representation for average areas, more like an worse case scenario.

---

Commands used:
```bash
# import indexes.sql (could be added to run.sh)
sudo -u postgres psql -d gis < /home/renderer/src/openstreetmap-carto/indexes.sql

# pre-render hamburg
./render_list_geo.pl -f -m ajt -n $THREADS -z 3 -Z 18 -x 9.72 -y 53.39 -X 10.33 -Y 53.75
```

**Comment by Overv** [comment]
Interesting to see that it actually gets slower at higher zoom levels, but I do think it's worthwhile to take into account the [recommended indexes](https://github.com/gravitystorm/openstreetmap-carto/blob/master/indexes.sql) for consistency. I will include those in the repository.

**Pull request closed without merging**
