### PR TITLE
Upgrade versions

### PR DESCRIPTION
**Pull request by galewis2**
Upgrades PostGIS, Postgres, Leaflet, carto, openstreetmap-carto.

Test with:

```
sudo docker build -t test .
sudo docker run -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/luxembourg.poly -v openstreetmap-data:/var/lib/postgresql/14/main test import
sudo docker run -p 8080:80 -v openstreetmap-data:/var/lib/postgresql/14/main -d test run
```

### CODE REVIEW

**Review by nielsole — APPROVED** [review]

**Comment by Istador** [comment]
Since this is a breaking change for users (they need to change their volume mount point and need to upgrade thir postgres database for existing volumes), please bump the major version.

The next version should be `2.0.0` with a `v2.0.0` tag in git.

**Comment by Istador** [comment]
Additional problem: This merged PR didn't made it to docker hub yet. Meaning the `latest` tag is still using postgres `12` and not `14`. But the `README.md` documentation here on Github is already mentioning volume mounts for version `14`. This confuses users.

See issue #259.

**Comment by Istador** [comment]
I'm also currently working on a solution for issue #257. I'll likely create a pull request for that soon (today or tomorrow).

(So you might want to wait with an official `2.0.0` release? Because otherwise that'd be another breaking change called `3.0.0`?)

**Comment by nielsole** [comment]
bumped to 2.0.0

**Pull request merged**
