### PR TITLE
README: Update link to switch2osm.org tile server guide

### PR DESCRIPTION
**Pull request by jdmonin**
Hello,

It looks like switch2osm moved the "manually build a tile server" page on their website.

This PR updates that link in the readme.

Thanks for maintaining this superbly easy to use tile server!
-Jeremy

### CODE REVIEW

**Comment by Overv** [comment]
@Istador Do you think we should switch to Ubuntu 20.04 LTS?

**Comment by Istador** [comment]
Yes, absolutely.

Even now when 18.04 LTS is still supported and receives updates, using a newer base image shows people looking at the Dockerfile of this project, that the project is still up-to-date and maintained. I remember that when my boss and I were choosing a docker image for our OSM server we mainly picked this one, because the other alternatives were using older ubuntu/debian base images.

A few days ago I was thinking about maybe providing a pull request for 20.04 and updates for the other software installations inside of the Dockerfile. But I'm lazy :D

Speaking of updates it'd generally be a good idea to regularly (e.g. weekly? monthly?) build the image again and publish it again with the newest version of the base image pulled (`docker build --pull`), even when there are no new features/developments to this project. That way users of this image (that check for updates for this image via `docker pull overv/openstreetmap-tile-sever`, `docker-compose pull` or `docker run --pull [...]`) will receive the latest security updates that are released with the base image and its package manager.

**Comment by Overv** [comment]
@Istador I've set up a cronjob to rebuild and push the latest release (tag `latest` and `1.6.0` currently) on a daily basis now.

**Comment by Istador** [comment]
> @Istador I've set up a cronjob to rebuild and push the latest release (tag `latest` and `1.6.0` currently) on a daily basis now.

Good to hear.

Is the cronjob using the [Makefile](https://github.com/Overv/openstreetmap-tile-server/blob/75e7714f200cf452bfbe2f249453125632773e48/Makefile), or is it manually calling `docker build` and `docker push`?

Because the Makefile isn't pulling the latest base image version before or while building.

When you automate something like this, you might wan't to add an additional automated test before pushing, to make sure, that the image published isn't broken (e.g. run the `test`, fetch `http://localhost:8080/tile/0/0/0.png` and check that its hash is unchanged).

**Comment by Overv** [comment]
@Istador The cronjob runs with --pull and --no-cache. I'll look into adding a test as well.

**Pull request merged**
