### PR TITLE
Upgrade to Postgresql 12

### PR DESCRIPTION
**Pull request by Y0ngg4n**
- Compile postgis manually
- Switch Directory to 12

Release Notes: 
[https://www.postgresql.org/about/news/1976/](https://www.postgresql.org/about/news/1976/)
Release Notes:
[https://www.postgresql.org/docs/release/12.0/](https://www.postgresql.org/docs/release/12.0/)

### CODE REVIEW

**Comment by Y0ngg4n** [comment]
@Istador oh sorry forgot that 😂 I will fix it.

**Comment by Y0ngg4n** [comment]
@Istador I fixed the Readme

**Comment by Shkarface** [comment]
There are some postgres 10 leftovers in the dockerfile, shouldn't they be changed to 12 as well?

**Comment by Overv** [comment]
@Shkarface Fixed, thanks.

**Pull request merged**
